[package]
edition = "2021"
license = "MIT OR Apache-2.0"
name = "parser"
version = "0.0.0"

[dependencies]
drop_bomb = "0.1.5"
syntax = {path = "../syntax"}
text-size = "1.1"
token = {path = "../token"}

[dev-dependencies]
expect-test = "1.1"
lexer = {path = "../lexer"}
