[package]
edition = "2021"
license = "MIT OR Apache-2.0"
name = "parser_bench"
version = "0.0.0"

[dependencies]
gen = {path = "../gen"}
lexer = {path = "../lexer"}
mimalloc = {version = "0.1.27", default-features = false}
parser = {path = "../parser"}
