[package]
edition = "2021"
license = "MIT OR Apache-2.0"
name = "hir_ty"
version = "0.0.0"

[dependencies]
arena = {path = "../arena"}
hir = {path = "../hir"}

[dev-dependencies]
lexer = {path = "../lexer"}
parser = {path = "../parser"}
