[package]
edition = "2021"
license = "MIT OR Apache-2.0"
name = "ast"
version = "0.0.0"

[dependencies]
syntax = {path = "../syntax"}
text-size = "1.1"

[dev-dependencies]
expect-test = "1.1"
lexer = {path = "../lexer"}
parser = {path = "../parser"}
