[package]
edition = "2021"
license = "MIT OR Apache-2.0"
name = "unnamedvm"
version = "0.1.0"

[dependencies]
anyhow = "1.0"
bincode = "1.0"
serde = {version = "1.0", features = ["derive"]}
thiserror = "1.0"
