[package]
edition = "2021"
license = "MIT OR Apache-2.0"
name = "lexer"
version = "0.0.0"

[dependencies]
logos = "0.12.0"
syntax = {path = "../syntax"}
text-size = "1.1"
token = {path = "../token"}

[dev-dependencies]
expect-test = "1.1"
