[package]
edition = "2018"
license = "MIT OR Apache-2.0"
name = "unnamedc"
version = "0.1.0"

[dependencies]
anyhow = "1.0"
ast = {path = "../ast"}
hir_lower = {path = "../hir_lower"}
lexer = {path = "../lexer"}
parser = {path = "../parser"}
